config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :artist, :song

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController

  def index
    @artists = Artist.all
  end
end

app/controllers/song_controller.rb
class SongController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artist/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
<p><%= artist.name %></p>
<% end %>
<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeworkDJ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/song/index.html.erb
<h1>Songs</h1>

<% @songs.each do |song| %>
<p><%= song.title %></p>
<p><%= song.artist[:name] %></p>

<% end %>
<%= link_to "Home", root_path %>

app/views/song/show.html.erb
<h1>hola</h1>

app/views/welcome/index.html.erb
<h1>Welcome!!!</h1>

<%= link_to "Artists", artist_index_path %>
<%= link_to "Songs", song_index_path %>